name: CI Pipeline to staging/production environment
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - staging
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    name: Setup, test, and build project
    env:
      PORT: 5001
    steps:
      - name: list files
        run: |
          ls -l
      - name: date
        run: |
          date
      - name: Say hello
        run: |
          echo "Hello World!"
      # - name: Checkout
      #   uses: actions/checkout@v4

      # - name: Install dependencies
      #   run: npm ci

      # - name: Check Style
      #   run: npm run eslint

      # - name: Test application
      #   run: npm test
